name: Staging

on:
  pull_request:
    branches: [release/*]
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/staging

jobs:
  # axum-api:
  #   uses: ./.github/workflows/axum-api.yml

  # svelte-ui:
  #   uses: ./.github/workflows/svelte-ui.yml

  build:
    # needs:
      # - axum-api
      # - svelte-ui
    runs-on: ubuntu-22.04

    environment: staging

    permissions:
      # For pushing to GHCR
      packages: write
      # For attestation step
      id-token: write
      attestations: write

    steps:
      - name: Install GitHub CLI
        run: |
          (type -p wget >/dev/null || (sudo apt update && sudo apt-get install wget -y)) \
            && sudo mkdir -p -m 755 /etc/apt/keyrings \
            && wget -qO- https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo tee /etc/apt/keyrings/githubcli-archive-keyring.gpg > /dev/null \
            && sudo chmod go+r /etc/apt/keyrings/githubcli-archive-keyring.gpg \
            && echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
            && sudo apt update \
            && sudo apt install gh -y
        
      - name: Delete all versions of package
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.repository_owner }}
        run: |
          echo "Deleting package: ${{ env.IMAGE_NAME }}"
          
          # List and delete all versions
          for version_id in $(gh api /user/packages/container/${{ env.IMAGE_NAME }}/versions --jq '.[].id'); do
            echo "Deleting version: $version_id"
            gh api \
              --method DELETE \
              /user/packages/container/${{ env.IMAGE_NAME }}/versions/$version_id
          done
