name: Publish Docker Image

on:
  push:
  pull_request:
    branches: [release]
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  axum-api:
    uses: ./.github/reusable-workflows/axum-api.yml

  svelte-ui:
    uses: ./.github/reusable-workflows/svelte-ui.yml

  build:
    needs:
      - axum-api
      - svelte-ui
    runs-on: ubuntu-22.04

    environment: staging

    permissions:
      packages: write

    steps:
      - uses: actions/checkout@v4
      # Download build artifacts
      - uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker-context/Dockerfile
          load: true
          push: true
          tags: |
            ghcr.io/beyond-chat/selfhosted:latest
            ghcr.io/beyond-chat/selfhosted:-0.0.1

      - name: Inspect
        run: |
          docker image inspect ghcr.io/beyond-chat/selfhosted:latest
