name: Staging

on:
  pull_request:
    branches: [release/*]
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/staging

jobs:
  # axum-api:
  #   uses: ./.github/workflows/axum-api.yml

  svelte-ui:
    uses: ./.github/workflows/svelte-ui.yml

  build:
    needs:
      # - axum-api
      - svelte-ui
    runs-on: ubuntu-22.04

    environment: staging

    permissions:
      # For pushing to GHCR
      packages: write
      # For attestation step
      id-token: write
      attestations: write

    steps:
      - name: Delete all versions of package
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.repository_owner }}
        run: |
          echo "Deleting package: ${{ env.IMAGE_NAME }}"
          
          # List and delete all versions
          for version_id in $(gh api /user/packages/container/${{ env.IMAGE_NAME }}/versions --jq '.[].id'); do
            echo "Deleting version: $version_id"
            gh api \
              --method DELETE \
              /user/packages/container/${{ env.IMAGE_NAME }}/versions/$version_id
          done
