name: Staging

on:
  pull_request:
    branches: [release/*]
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}-staging

jobs:
  axum-api:
    uses: ./.github/workflows/axum-api.yml

  svelte-ui:
    uses: ./.github/workflows/svelte-ui.yml

  build:
    needs:
      - axum-api
      - svelte-ui
    runs-on: ubuntu-22.04

    environment: staging

    permissions:
      # For pushing to GHCR
      packages: write

    steps:
      - uses: actions/checkout@v4
      # Download build artifacts
      - uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker-infra/Dockerfile
          load: true
          push: true
          tags: latest
          # labels: ${{ github.event.head_ref }}

      # - name: Inspect
      #   run: |
      #     # Log in to GHCR again to ensure authentication for inspection
      #     echo "${{ secrets.GITHUB_TOKEN }}" | docker login ${{ env.REGISTRY }} -u ${{ github.actor }} --password-stdin
      #     # Inspect the specific image
      #     docker image inspect ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
